import { withDefaultPresentation } from "./presentation"
import type { HomepageSectionInput } from "./types"

export type HomepageSectionSeed = Required<
  Pick<HomepageSectionInput, "key" | "type" | "sort_order" | "active">
> &
  Omit<HomepageSectionInput, "key" | "type" | "sort_order" | "active">

/** Active homepage sections in render order (matches Shopify index.json). */
export const HOMEPAGE_SECTION_ORDER_BY_KEY = [
  "hero",
  "trust_ribbon",
  "founding_drop",
  "feeling_grid",
  "editorial_feature",
  "gift_block",
  "proof_strip",
  "why_horo",
] as const

export const DEFAULT_HOMEPAGE_SECTIONS: HomepageSectionSeed[] = [
  {
    key: "hero",
    type: "hero",
    title_en: "Wear What You Feel",
    title_ar: "إلبس اللي بتحس بيه",
    body_en: "Artist-made T-shirts for feelings, identity, and meaningful gifts.",
    body_ar: "تيشيرتات من فنانين للمشاعر والهوية والهدايا اللي لها معنى.",
    primary_cta_label_en: "Shop the Drop",
    primary_cta_label_ar: "تسوق الإطلاق",
    primary_cta_href: "/products",
    secondary_cta_label_en: "A Closer Look",
    secondary_cta_label_ar: "نظرة أقرب",
    secondary_cta_href: "/#editorial-feature",
    image_src: "/images/hero/home-hero-wear-feel.png",
    image_alt_en: "Model wearing HORO graphic tee — Wear What You Feel",
    image_alt_ar: "عارض يرتدي تيشيرت هورو — إلبس اللي بتحس بيه",
    sort_order: 0,
    active: true,
    payload: withDefaultPresentation("hero", {
      soundbite_en: "Find Your Rhythm",
      soundbite_ar: "اكتشف إيقاعك",
      canvas_en: "We are the canvas. You are the story.",
      canvas_ar: "إحنا القماش. إنت القصة.",
      story_system: "HORO V1.9 / StoryBrand 2 soundbite strategy",
      palette_roles: {
        page_canvas: "#FFF7F5",
        breath_panel: "#FEE5E2",
        root_text: "#4F111F",
        pulse_action: "#8C2340",
        usage: "Soft/white canvas first; Breath for trust/story/gift panels; Root for depth and text; Pulse only for CTAs, badges, and active states.",
      },
    }),
  },
  {
    key: "trust_ribbon",
    type: "trust_ribbon",
    sort_order: 10,
    active: true,
    payload: withDefaultPresentation("trust_ribbon", {
      items: [
        { key: "artistMade", label_en: "Artist-made", label_ar: "تصميم فنانين", icon: "artistSigned" },
        { key: "printedEgypt", label_en: "Printed in Egypt", label_ar: "مطبوعة في مصر", icon: "printedEgypt" },
        { key: "paymentAtCheckout", label_en: "Payment at checkout", label_ar: "الدفع عند الدفع", icon: "codExchange" },
        { key: "clearFitDetails", label_en: "Clear fit", label_ar: "مقاس واضح", icon: "clearFitDetails" },
        { key: "whatsappSupport", label_en: "WhatsApp help", label_ar: "مساعدة واتساب", icon: "whatsappSupport" },
      ],
      trustStripItems: [
        { key: "artistMade", label: { en: "Artist-made", ar: "تصميم فنانين" } },
        { key: "printedEgypt", label: { en: "Printed in Egypt", ar: "مطبوعة في مصر" } },
        { key: "paymentAtCheckout", label: { en: "Payment at checkout", ar: "الدفع عند الدفع" } },
        { key: "clearFitDetails", label: { en: "Clear fit", ar: "مقاس واضح" } },
        { key: "whatsappSupport", label: { en: "WhatsApp help", ar: "مساعدة واتساب" } },
      ],
    }),
  },
  {
    key: "primary_routes",
    type: "primary_routes",
    eyebrow_en: "SHOP YOUR WAY",
    eyebrow_ar: "تسوق بطريقتك",
    title_en: "Start with feeling, gift, or moment",
    title_ar: "ابدأ بالشعور أو الهدية أو المناسبة",
    sort_order: 60,
    active: false,
    payload: {
      giftRoutes: [
        {
          key: "gift_hub",
          label: { en: "Shop Gifts", ar: "تسوّق الهدايا" },
          href: "/gifts",
        },
      ],
    },
  },
  {
    key: "founding_drop",
    type: "founding_drop",
    eyebrow_en: "THE FOUNDING DROP",
    eyebrow_ar: "الإطلاق الأول",
    title_en: "Wearable artwork for signs, moods, and personal stories.",
    title_ar: "فن قابل للّبس للأبراج والمزاج والقصص الشخصية.",
    body_en: null,
    body_ar: null,
    image_src: "/images/homepage-reference/founding-drop-campaign.png",
    image_alt_en: "The Founding Drop — wearable artwork",
    image_alt_ar: "الإطلاق الأول — فن قابل للّبس",
    primary_cta_label_en: "Shop Now",
    primary_cta_label_ar: "تسوّق الإطلاق الأول",
    primary_cta_href: "/products",
    secondary_cta_label_en: "A Closer Look",
    secondary_cta_label_ar: "نظرة أقرب",
    secondary_cta_href: "/#editorial-feature",
    sort_order: 20,
    active: true,
    payload: withDefaultPresentation("founding_drop", {
      limit: 5,
    }),
  },
  {
    key: "featured_piece",
    type: "featured_piece",
    eyebrow_en: "FEATURED PIECE",
    eyebrow_ar: "قطعة مختارة",
    title_en: "One design to inspect first",
    title_ar: "تصميم تبدأ به",
    primary_cta_label_en: "View the piece",
    primary_cta_label_ar: "شاهد القطعة",
    primary_cta_href: "/products",
    sort_order: 70,
    active: false,
  },
  {
    key: "feeling_grid",
    type: "feeling_grid",
    eyebrow_en: null,
    eyebrow_ar: null,
    title_en: "Shop by Meaning",
    title_ar: "تسوّق حسب المعنى",
    body_en: null,
    body_ar: null,
    primary_cta_label_en: null,
    primary_cta_label_ar: null,
    primary_cta_href: null,
    sort_order: 30,
    active: true,
    payload: withDefaultPresentation("feeling_grid", {
      feelings: [
        { slug: "mood", label: { en: "Mood", ar: "مزاج" }, href: "/products?category=mood" },
        { slug: "zodiac", label: { en: "Zodiac", ar: "الأبراج" }, href: "/products?category=zodiac" },
        { slug: "gift-ready", label: { en: "Gift Ready", ar: "جاهزة للهدايا" }, href: "/gifts" },
        { slug: "lifestyle", label: { en: "Lifestyle", ar: "نمط حياة" }, href: "/products?category=lifestyle" },
      ],
    }),
  },
  {
    key: "gift_block",
    type: "gift_block",
    eyebrow_en: "GIFT READY",
    eyebrow_ar: "جاهزة للهدايا",
    title_en: "More than a gift.",
    title_ar: "أكثر من هدية.",
    body_en: "A feeling they'll wear.",
    body_ar: "إحساس هيلبسوه.",
    primary_cta_label_en: "Find a Gift",
    primary_cta_label_ar: "تسوق الهدايا",
    primary_cta_href: "/gifts",
    image_src: "/images/homepage-reference/gift-box.png",
    image_alt_en: "HORO gift-ready package.",
    image_alt_ar: "تغليف هورو جاهز للهدايا.",
    sort_order: 45,
    active: true,
    payload: withDefaultPresentation("gift_block", {}),
  },
  {
    key: "editorial_feature",
    type: "editorial_feature",
    eyebrow_en: "A CLOSER LOOK",
    eyebrow_ar: "نظرة أقرب",
    title_en: "Calm Inside",
    title_ar: "هدوء من الداخل",
    body_en: "Artwork, fit, and print details in one closer view.",
    body_ar: "العمل الفني والمقاس وتفاصيل الطباعة في نظرة أقرب.",
    image_src: "/images/homepage-reference/editorial-calm-inside.png",
    image_alt_en: "Calm Inside — artwork detail",
    image_alt_ar: "هدوء من الداخل — تفاصيل العمل الفني",
    primary_cta_label_en: "Shop the Piece",
    primary_cta_label_ar: "تسوّق القطعة",
    primary_cta_href: "/products/calm-inside",
    sort_order: 35,
    active: true,
    payload: withDefaultPresentation("editorial_feature", {
      variant: "closer_look",
      anchorId: "editorial-feature",
    }),
  },
  {
    key: "proof_strip",
    type: "proof_strip",
    sort_order: 48,
    active: true,
  },
  {
    key: "why_horo",
    type: "why_horo",
    eyebrow_en: "OUR STORY",
    eyebrow_ar: "قصتنا",
    title_en: "We are the canvas. You are the story.",
    title_ar: "إحنا القماش. إنت القصة.",
    body_en: null,
    body_ar: null,
    image_src: "/images/homepage-reference/our-story.png",
    image_alt_en: "HORO — artist process and product",
    image_alt_ar: "هورو — عمل الفنان والمنتج",
    primary_cta_label_en: "Read our story",
    primary_cta_label_ar: "اقرأ قصتنا",
    primary_cta_href: "/about",
    sort_order: 50,
    active: true,
    payload: withDefaultPresentation("why_horo", {
      pillars: [
        {
          key: "localArtists",
          icon: "localArtists",
          title: { en: "Art that speaks feelings", ar: "فن بيعبر عن المشاعر" },
          body: { en: "Original illustrations for real emotions.", ar: "رسومات أصلية لمشاعر حقيقية." },
        },
        {
          key: "madeToFeelPersonal",
          icon: "madeToFeelPersonal",
          title: { en: "Made with intention", ar: "مصنوعة بنية" },
          body: { en: "Mindful materials. Responsible production.", ar: "خامات مختارة وإنتاج مسؤول." },
        },
        {
          key: "realProofOnly",
          icon: "realProofOnly",
          title: { en: "For every version of you", ar: "لكل نسخة منك" },
          body: {
            en: "Pieces that move with your moments — not one generic graphic for everyone.",
            ar: "قطع تتحرك مع لحظاتك — مش رسمة عامة لكل الناس.",
          },
        },
      ],
    }),
  },
  {
    key: "artist_spotlight",
    type: "artist_spotlight",
    eyebrow_en: "ARTIST PROOF",
    eyebrow_ar: "دليل الفنان",
    title_en: "Original artwork you can wear",
    title_ar: "عمل فني أصلي تقدر تلبسه",
    sort_order: 80,
    active: false,
  },
  {
    key: "seen_on_you",
    type: "seen_on_you",
    eyebrow_en: "SEEN ON YOU",
    eyebrow_ar: "كما يظهر عليكم",
    title_en: "Reviews and UGC when available",
    title_ar: "آراء وصور العملاء عند توفرها",
    sort_order: 90,
    active: false,
  },
]
