import { withDefaultPresentation } from "./presentation"
import type { HomepageSectionInput } from "./types"

export type HomepageSectionSeed = Required<
  Pick<HomepageSectionInput, "key" | "type" | "sort_order" | "active">
> &
  Omit<HomepageSectionInput, "key" | "type" | "sort_order" | "active">

/** Active homepage sections in render order (matches Shopify index.json). */
export const HOMEPAGE_SECTION_ORDER_BY_KEY = [
  "hero",
  "primary_routes",
  "trust_ribbon",
  "founding_drop",
  "feeling_grid",
  "editorial_feature",
  "why_horo",
  "seen_on_you",
] as const

export const DEFAULT_HOMEPAGE_SECTIONS: HomepageSectionSeed[] = [
  {
    key: "hero",
    type: "hero",
    title_en: "Wear What You Feel",
    title_ar: "إلبس اللي بتحس بيه",
    body_en: "Artist-made T-shirts for feelings, identity, and meaningful gifts.",
    body_ar: "تيشيرتات من فنانين للمشاعر والهوية والهدايا اللي لها معنى.",
    primary_cta_label_en: "Shop the Drop",
    primary_cta_label_ar: "تسوّق الإطلاق",
    primary_cta_href: "/products",
    secondary_cta_label_en: "See the Details",
    secondary_cta_label_ar: "شاهد التفاصيل",
    secondary_cta_href: "/#editorial-feature",
    image_src: "/images/hero/home-hero-wear-feel.png",
    image_alt_en: "Model wearing HORO graphic tee — Wear What You Feel",
    image_alt_ar: "عارض يرتدي تيشيرت هورو — إلبس اللي بتحس بيه",
    sort_order: 0,
    active: true,
    payload: withDefaultPresentation("hero", {
      soundbite_en: "Find Your Rhythm",
      soundbite_ar: "اكتشف إيقاعك",
      canvas_en: "We are the canvas. You are the story.",
      canvas_ar: "إحنا القماش. إنت القصة.",
      story_system: "HORO V1.9 / StoryBrand 2 soundbite strategy",
      carouselMode: true,
      selectedVariant: "drop",
      heroVariants: [
        {
          key: "drop",
          title: { en: "Wear What You Feel", ar: "إلبس اللي بتحس بيه" },
          body: {
            en: "Artist-made T-shirts for feelings, identity, and meaningful gifts.",
            ar: "تيشيرتات من فنانين للمشاعر والهوية والهدايا اللي لها معنى.",
          },
          primaryCta: {
            label: { en: "Shop the Drop", ar: "تسوّق الإطلاق" },
            href: "/products",
          },
          imageSrc: "/images/hero/home-hero-wear-feel.png",
        },
        {
          key: "collections",
          title: { en: "Five pieces. Real meanings.", ar: "خمس قطع. معاني حقيقية." },
          body: {
            en: "A focused launch, not a category maze — choose the piece that fits today.",
            ar: "إطلاق مركز، مش متاهة تصنيفات — اختار القطعة اللي تناسبك النهارده.",
          },
          primaryCta: {
            label: { en: "View the pieces", ar: "شاهد القطع" },
            href: "/products",
          },
          imageSrc: "/images/homepage-reference/editorial-artwork-detail.png",
        },
        {
          key: "gifts",
          title: { en: "Gift-ready pieces", ar: "قطع جاهزة للهدايا" },
          body: {
            en: "Thoughtful picks with WhatsApp size help before you order.",
            ar: "اختيارات مدروسة مع مساعدة مقاس على واتساب قبل الطلب.",
          },
          primaryCta: {
            label: { en: "Shop Gifts", ar: "تسوّق الهدايا" },
            href: "/gifts",
          },
          imageSrc: "/images/homepage-reference/gift-box.png",
        },
      ],
      palette_roles: {
        page_canvas: "#FFF7F5",
        breath_panel: "#FEE5E2",
        root_text: "#4F111F",
        pulse_action: "#8C2340",
        usage: "Soft/white canvas first; Breath for trust/story/gift panels; Root for depth and text; Pulse only for CTAs, badges, and active states.",
      },
    }),
  },
  {
    key: "trust_ribbon",
    type: "trust_ribbon",
    sort_order: 15,
    active: true,
    payload: withDefaultPresentation("trust_ribbon", {
      items: [
        { key: "artistMade", label_en: "Artist-made", label_ar: "تصميم فنانين", icon: "artistSigned" },
        { key: "printedEgypt", label_en: "Printed in Egypt", label_ar: "مطبوعة في مصر", icon: "printedEgypt" },
        { key: "paymentAtCheckout", label_en: "Payment at checkout", label_ar: "الدفع عند الدفع", icon: "codExchange" },
        { key: "exchange14d", label_en: "14-day exchange — see policy", label_ar: "استبدال ١٤ يوم — راجع السياسة", icon: "exchange14d" },
        { key: "whatsappSupport", label_en: "WhatsApp help", label_ar: "مساعدة واتساب", icon: "whatsappSupport" },
      ],
      trustStripItems: [
        { key: "artistMade", label: { en: "Artist-made", ar: "تصميم فنانين" } },
        { key: "printedEgypt", label: { en: "Printed in Egypt", ar: "مطبوعة في مصر" } },
        { key: "paymentAtCheckout", label: { en: "Payment at checkout", ar: "الدفع عند الدفع" } },
        { key: "exchange14d", label: { en: "14-day exchange — see policy", ar: "استبدال ١٤ يوم — راجع السياسة" } },
        { key: "whatsappSupport", label: { en: "WhatsApp help", ar: "مساعدة واتساب" } },
      ],
    }),
  },
  {
    key: "primary_routes",
    type: "primary_routes",
    eyebrow_en: "SIGNATURE PIECES",
    eyebrow_ar: "قطع مميزة",
    title_en: "Choose the piece",
    title_ar: "اختار القطعة",
    sort_order: 10,
    active: true,
    payload: {
      items: [
        {
          key: "walk_alone",
          label: { en: "Walk Alone", ar: "امشي لوحدك" },
          subtitle: { en: "A signature piece for choosing your own path.", ar: "قطعة مميزة لمن يختار طريقه بنفسه." },
          href: "/products/quiet-revolt",
          productHandle: "quiet-revolt",
          accent: "#241f21",
          imageSrc: "/images/homepage-reference/product-walk-alone.png",
        },
        {
          key: "i_care",
          label: { en: "I Care", ar: "اهتم" },
          subtitle: { en: "A direct tee for the ones who feel deeply.", ar: "تيشيرت مباشر لمن يشعر بعمق." },
          href: "/products/the-weight-of-light",
          productHandle: "the-weight-of-light",
          accent: "#4F111F",
          imageSrc: "/images/homepage-reference/product-i-care.png",
        },
        {
          key: "i_dont_care",
          label: { en: "I Don't Care", ar: "مش فارق" },
          subtitle: { en: "A statement tee for the ones who own their freedom.", ar: "تيشيرت موقف لمن يملك حريته." },
          href: "/products/trends-next-wave",
          productHandle: "trends-next-wave",
          accent: "#241f21",
          imageSrc: "/images/homepage-reference/product-i-dont-care.png",
        },
      ],
    },
  },
  {
    key: "founding_drop",
    type: "founding_drop",
    eyebrow_en: "FEATURED PIECES",
    eyebrow_ar: "قطع مختارة",
    title_en: "Our first 5 pieces. Limited quantities.",
    title_ar: "أول ٥ قطع. كميات محدودة.",
    body_en: null,
    body_ar: null,
    image_src: "/images/homepage-reference/founding-drop-campaign.png",
    image_alt_en: "The Founding Drop — wearable artwork",
    image_alt_ar: "الإطلاق الأول — فن قابل للّبس",
    primary_cta_label_en: "Shop the Drop",
    primary_cta_label_ar: "تسوّق الإطلاق",
    primary_cta_href: "/products",
    secondary_cta_label_en: "See the Details",
    secondary_cta_label_ar: "شاهد التفاصيل",
    secondary_cta_href: "/#editorial-feature",
    sort_order: 20,
    active: true,
    payload: withDefaultPresentation("founding_drop", {
      limit: 5,
    }),
  },
  {
    key: "featured_piece",
    type: "featured_piece",
    eyebrow_en: "FEATURED PIECE",
    eyebrow_ar: "قطعة مختارة",
    title_en: "One design to inspect first",
    title_ar: "تصميم تبدأ به",
    primary_cta_label_en: "View Design",
    primary_cta_label_ar: "شاهد التصميم",
    primary_cta_href: "/products",
    sort_order: 70,
    active: false,
  },
  {
    key: "feeling_grid",
    type: "feeling_grid",
    eyebrow_en: null,
    eyebrow_ar: null,
    title_en: "Shop by Feeling",
    title_ar: "تسوّق حسب الشعور",
    body_en: null,
    body_ar: null,
    primary_cta_label_en: null,
    primary_cta_label_ar: null,
    primary_cta_href: null,
    sort_order: 30,
    active: true,
    payload: withDefaultPresentation("feeling_grid", {
      feelings: [
        {
          slug: "zodiac",
          label: { en: "Zodiac Signs", ar: "الأبراج" },
          subtitle: { en: "12 designs", ar: "١٢ تصميم" },
          href: "/products?category=zodiac",
          iconSlug: "zodiac",
        },
        {
          slug: "mood",
          label: { en: "Mood", ar: "مزاج" },
          subtitle: { en: "Feelings you wear", ar: "مشاعر تلبسها" },
          href: "/products?category=mood",
          iconSlug: "mood",
        },
        {
          slug: "lifestyle",
          label: { en: "Lifestyle", ar: "نمط حياة" },
          subtitle: { en: "Daily pieces", ar: "قطع يومية" },
          href: "/products?category=lifestyle",
          iconSlug: "lifestyle",
        },
        {
          slug: "for-someone",
          label: { en: "For Someone", ar: "لشخص عزيز" },
          subtitle: { en: "Gifting", ar: "هدايا" },
          href: "/gifts",
          iconSlug: "gift",
        },
      ],
    }),
  },
  {
    key: "gift_block",
    type: "gift_block",
    eyebrow_en: "WHEN YOU'RE GIFTING",
    eyebrow_ar: "لما تهدي",
    title_en: "More than a gift.",
    title_ar: "أكثر من هدية.",
    body_en: "Thoughtful picks for someone on your mind.",
    body_ar: "اختيارات مدروسة لشخص على بالك.",
    primary_cta_label_en: "Shop Gifts",
    primary_cta_label_ar: "تسوّق الهدايا",
    primary_cta_href: "/gifts",
    image_src: "/images/homepage-reference/gift-box.png",
    image_alt_en: "HORO gift-ready package.",
    image_alt_ar: "تغليف هورو جاهز للهدايا.",
    sort_order: 45,
    active: false,
    payload: withDefaultPresentation("gift_block", {}),
  },
  {
    key: "editorial_feature",
    type: "editorial_feature",
    eyebrow_en: "A CLOSER LOOK",
    eyebrow_ar: "نظرة أقرب",
    title_en: "Calm Inside",
    title_ar: "هدوء من الداخل",
    body_en: "Artwork, fit, and print details in one closer view.",
    body_ar: "العمل الفني والمقاس وتفاصيل الطباعة في نظرة أقرب.",
    image_src: "/images/homepage-reference/editorial-calm-inside.png",
    image_alt_en: "Calm Inside — styled HORO product detail",
    image_alt_ar: "هدوء من الداخل — تفاصيل منتج هورو",
    primary_cta_label_en: "View Design",
    primary_cta_label_ar: "شاهد التصميم",
    primary_cta_href: "/products/calm-inside",
    sort_order: 35,
    active: true,
    payload: withDefaultPresentation("editorial_feature", {
      variant: "shop_the_look",
      anchorId: "editorial-feature",
      fallbackProductHandle: "calm-inside",
      productHandles: ["calm-inside", "walk-alone-tee"],
    }),
  },
  {
    key: "proof_strip",
    type: "proof_strip",
    sort_order: 48,
    active: false,
  },
  {
    key: "why_horo",
    type: "why_horo",
    eyebrow_en: "THIS IS HORO",
    eyebrow_ar: "هذا هو هورو",
    title_en: "Find Your Rhythm",
    title_ar: "اكتشف إيقاعك",
    body_en: "HORO is more than clothing — it's a language of self-expression. Artist-made pieces for feelings, identity, and meaningful gifts.",
    body_ar: "هورو أكثر من ملابس — لغة للتعبير عن الذات. قطع من فنانين للمشاعر والهوية والهدايا اللي لها معنى.",
    image_src: "/images/homepage-reference/our-story-artist.png",
    image_alt_en: "HORO — artist process and studio",
    image_alt_ar: "هورو — عمل الفنان والمنتج",
    primary_cta_label_en: "Read our story",
    primary_cta_label_ar: "اقرأ قصتنا",
    primary_cta_href: "/about",
    sort_order: 45,
    active: true,
    payload: withDefaultPresentation("why_horo", {
      pillars: [
        {
          key: "localArtists",
          icon: "localArtists",
          title: { en: "Art that speaks feelings", ar: "فن بيعبر عن المشاعر" },
          body: { en: "Original illustrations for real emotions.", ar: "رسومات أصلية لمشاعر حقيقية." },
        },
        {
          key: "madeToFeelPersonal",
          icon: "madeToFeelPersonal",
          title: { en: "Made with intention", ar: "مصنوعة بنية" },
          body: { en: "Mindful materials. Responsible production.", ar: "خامات مختارة وإنتاج مسؤول." },
        },
        {
          key: "realProofOnly",
          icon: "realProofOnly",
          title: { en: "For every version of you", ar: "لكل نسخة منك" },
          body: {
            en: "Pieces that move with your moments — not one generic graphic for everyone.",
            ar: "قطع تتحرك مع لحظاتك — مش رسمة عامة لكل الناس.",
          },
        },
      ],
    }),
  },
  {
    key: "artist_spotlight",
    type: "artist_spotlight",
    eyebrow_en: "ARTIST PROOF",
    eyebrow_ar: "دليل الفنان",
    title_en: "Original artwork you can wear",
    title_ar: "عمل فني أصلي تقدر تلبسه",
    sort_order: 80,
    active: false,
  },
  {
    key: "seen_on_you",
    type: "seen_on_you",
    eyebrow_en: "YOU WEAR IT BEST",
    eyebrow_ar: "أنتم ترتدونه بأجمل شكل",
    title_en: "Real people. Real stories.",
    title_ar: "ناس حقيقيون. قصص حقيقية.",
    sort_order: 50,
    active: true,
    payload: {
      gallery: [
        {
          imageSrc: "/images/proof/back-fit-card.svg",
          imageAlt: { en: "Customer wearing HORO — back fit proof.", ar: "عميل يرتدي هورو — دليل المقاس." },
        },
        {
          imageSrc: "/images/proof/macro-detail-card.svg",
          imageAlt: { en: "Close-up of HORO print quality.", ar: "تفاصيل مقربة لجودة طباعة هورو." },
        },
        {
          imageSrc: "/images/proof/fabric-tag-card.svg",
          imageAlt: { en: "Fabric and tag detail on a HORO tee.", ar: "تفاصيل القماش والبطاقة على تيشيرت هورو." },
        },
        {
          imageSrc: "/images/proof/weight-scale-card.svg",
          imageAlt: { en: "Weight and quality proof for HORO cotton.", ar: "دليل الوزن والجودة لقطن هورو." },
        },
      ],
    },
  },
]
